language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
service: mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
# command to run tests
script: pytest
