---
- hosts: "{{myhost}}"
  tasks:
    - name: "Free exec sql file to database {{dbname}}"
      mysql_exec: 
        db: "{{dbname}}" 
        user: "root" 
        password: "asdf10" 
        type: file
        file: "./test.sql"
      register: res

    - debug: var=res
