---
- hosts: "{{myhost}}"
  tasks:
    - name: "Restore of database {{dbname}}"
      mysql_dump: 
        action: restore
        db: "{{dbname}}" 
        user: "root" 
        password: "asdf10" 
        path: "./{{dbname}}.dmp"
#        exclude: true 
#        tables:
#          - AssetEntry
      register: res

    - debug: var=res
